---

- name: See if Default MariaDB Exists
  command: rpm -q MariaDB
  register: old_mariadb_installed
  failed_when: old_mariadb_installed.rc > 1

- name: Stop MariaDB if Installed
  systemd:
   name="mariadb"
   state="stopped"
  when: old_mariadb_installed.rc == 0

- name: Remove Existing MariaDB Install
  yum:
   name="{{ item }}"
   state="absent"
  with_items:
   - "MariaDB"
   - "MariaDB-server"
   - "mysql-libs"
  when: old_mariadb_installed.rc == 0
- name: Allow MariaDB Port(s) In SELinux
  seboolean:
    name="mysql_connect_any"
    state="true"
    persistent="yes"

- name: Explicitly Allow mysql_extra_port
  seport:
    ports="{{ mysql_extra_port }}"
    proto="tcp"
    setype="mysqld_port_t"
    state="present"
- name: Flush Yum Cache
  command: yum clean all

